name: GOLang-Build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  go-script:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Go Scripts 
        run: |
           echo "Hello World"
        shell: bash {0}
