name: GO-Builds

on: 
  push: 
    branches: 
    - main 
    - staging
    - develop 
  pull_request: 
    branches: 
    - main 
    - staging 
    - develop

jobs:
  go-script:
    runs-on: 'go'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Go Scripts 
        run: |
           go version
           go run hello.go
        shell: bash {0}


  go-conditions:
    runs-on: 'go'
    needs: go-script
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Go Conditions
        run: |
           go run my_tutorials/conditionals/main.go
        shell: bash {0}


  go-algorithms:
    runs-on: 'go'
    needs: go-script
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Minutes To Seconds
        run: |
           go run datastructure_algorithms/convert_mins_secs/main.go
        shell: bash {0}
