name: GoLang Project Pipelines

on: push

jobs:
  go-prereqs:
    name: Go Prerequisites
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Check Out
        run: |
          ls

  go-codes:
    name: Build Go Codes
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code2
        uses: actions/checkout@v2

      - name: Test Check Out2
        run: |
          ls
