name: Golang-Builds

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  check_suite:
    types:
      - completed
  status: {}

jobs:
  build:
    runs-on: self-hosted
    container:
      image: golang:1.14-buster   

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Hello World
        run: |
          go run hello.go

      - name: Make All
        run: |
          make all

      - name: Run Console App
        run: |
          go run console_code/console-code.go 3 4

      - name: Run Two Sum Algorithm
        run: |
          cd datastructure_algorithms/two_sum/
          go run twosum.go
          go test -v -run TestTwoSum1
          go test -v -run TestTwoSum2

      - name: Slack Notification Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_TITLE: Build Succeeded
            SLACK_COLOR: '#00cc00'

      - name: Slack Notification Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_TITLE: Build Failed
            SLACK_COLOR: '#ff0000'
