name: GoLang Project Pipelines

on: push

jobs:
  go-main:
    name: Go Jobs
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Check Out
        run: |
          ls
