name: Golang-Builds

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main 

jobs:
  build-prereqs:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Hello World
        run: |
          go run hello.go

      - name: Make All
        run: |
          make all


  go-sampleproblems:
    runs-on: 'ubuntu-latest'
    needs: build-prereqs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Basic File Processing
        run: |
          go run file_processing/filep.go


  go-cheetsheet:
    runs-on: 'ubuntu-latest'
    needs: build-prereqs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Console App
        run: |
          go run console_code/console-code.go 3 4




  algorithms:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Two Sum Algorithm
        run: |
          cd datastructure_algorithms/two_sum/
          go run twosum.go
          go test -v -run TestTwoSum1
          go test -v -run TestTwoSum2
