name: Golang-Builds

on: [push]

jobs:
  build-prereqs:
    runs-on: self-hosted

    container:
      image: golang:1.14-buster   

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Hello World
        run: |
          go version
          go run hello.go

      #- name: Run Console App
      #  run: |
      #    go run console_code/console-code.go 3 4
