name: Builds

on: [push] 

jobs:
  build-prereqs:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Make All
        run: |
          make all

      - uses: nashmaniac/create-issue-action@v1.1
        if: ${{ failure() }} # only run when this job is failed.
        name: Create Issue Action
        with:
    	  title: Linter Failed
	  token: ${{secrets.GITHUB_TOKEN}}
	  assignees: ${{github.actor}}
	  labels: refactoring-needed, help needed
	  body: Workflow failed for commit ${{github.sha}}


  #go-sampleproblems:
  #  runs-on: 'ubuntu-latest'
  #  needs: build-prereqs
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v2

  #    - name: Basic File Processing
  #      run: |
  #        go run file_processing/filep.go

  #    - name: Factorial Recursion
  #      run: |
  #        go run functions/factorial.go

  #go-cheetsheet:
  #  runs-on: 'ubuntu-latest'
  #  needs: build-prereqs
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v2

  #    - name: Run Console App
  #      run: |
  #        go run console_code/console-code.go 3 4

  #go-unittests:
  #  runs-on: 'ubuntu-latest'
  #  needs: build-prereqs
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v2

  #    - name: Run Sample Go Unit Tests
  #      run: |
  #        cd unit_tests
  #        go test -v -cover





  #algorithms-reqs:
  #  runs-on: 'ubuntu-latest'
  #  steps:
  #    - name: Algorithm Reqs
  #      run: |
  #        echo "Algorithms Section"

  #algorithms:
  #  runs-on: 'ubuntu-latest'
  #  needs: algorithms-reqs
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v2

  #    - name: Run Two Sum Algorithm
  #      run: |
  #        cd datastructure_algorithms/two_sum/
  #        go run twosum.go
  #        go test -v -run TestTwoSum1
  #        go test -v -run TestTwoSum2



  #deploy:
  #  runs-on: 'ubuntu-latest'
  #  needs: [algorithms,go-cheetsheet,go-sampleproblems,go-unittests]
  #  steps:
  #    - name: Deploy Artifacts
  #      run: |
  #        echo "Code Pipeline Completed"
