name: GO-Builds

on: [push] 

jobs:
  go-script:
    runs-on: 'go'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Go Scripts 
        run: |
           echo $PATH
           #go run hello.go
        shell: bash {0}
