name: GO-CICD-Builds

on: 
  push: 
    branches: 
    - main 
    - staging
    - develop 
  pull_request: 
    branches: 
    - main 
    - staging 
    - develop

jobs:
  go-script:
    runs-on: 'cicd'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Go Scripts 
        run: |
           go version
           go run hello.go
        shell: bash {0}


  go-conditions:
    runs-on: 'cicd'
    needs: go-script
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Go Conditions
        run: |
           go run my_tutorials/conditionals/main.go-orig
        shell: bash {0}

      - name: Slack Notification Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_TITLE: GO-Conditions Build Succeeded
            SLACK_COLOR: '#00cc00'
            SLACK_MESSAGE: 'Build Passed. Merge and Deploy'

      - name: Slack Notification Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_TITLE: GO-Conditions Build Failed
            SLACK_COLOR: '#ff0000'
            SLACK_MESSAGE: 'Build Failed. Do not deploy this build'




  go-algorithms:
    runs-on: 'cicd'
    needs: go-script
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Minutes To Seconds
        run: |
           go run datastructure_algorithms/convert_mins_secs/main.go
        shell: bash {0}

      - name: Slack Notification Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_TITLE: GO-Algorithms Build Succeeded
            SLACK_COLOR: '#00cc00'
            SLACK_MESSAGE: 'Build Passed. Merge and Deploy'

      - name: Slack Notification Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_TITLE: GO-Algorithms Build Failed
            SLACK_COLOR: '#ff0000'
            SLACK_MESSAGE: 'Build Failed. Do not deploy this build'
