name: GoLang Project Pipeline

on: push

jobs:
  go-prereqs:
    name: Go Prerequisites
    runs-on: 'ubuntu-latest'
    env:
       GO_VERSION: 1.15.5

    steps:
      - name: Install Go ${{ env.GO_VERSION }}
        run: |
          sudo wget https://dl.google.com/go/go${{ env.GO_VERSION }}.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go${{ env.GO_VERSION }}.linux-amd64.tar.gz
          sudo rm go${{ env.GO_VERSION }}.linux-amd64.tar.gz
          /usr/local/go/bin/go version


  go-codes:
    name: Build Go Codes
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test Hello Code
        run: |
          go run hello.go

      - name: Other Codes
        run: |
          go run console_code/console-code.go 3 4
