name: CI-Builds

on: [push] 

jobs:
  build-prereqs:
    runs-on: 'go'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test Shell Script 
        shell: bash {0}
        run: |
           ls
