name: GO-Manual-Build

on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - main
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Build Environment'     
        required: true
        default: 'prod'
      Version:
        description: 'Deploy Version'  
        required: false




jobs:
  go-script:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Go Scripts 
        run: |
           #go version
           #go run hello.go
           echo "Hello World"
        shell: bash {0}

