name: GO-Manual-Build

on: 
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Build Environment'     
        required: true
        default: 'prod'
      Version:
        description: 'Deploy Version'  
        required: false




jobs:
  go-script:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Go Scripts 
        run: |
           #go version
           #go run hello.go
           echo "Hello World"
        shell: bash {0}


  #go-conditions:
  #  runs-on: 'cicd'
  #  needs: go-script
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v2

  #    - name: Go Conditions
  #      run: |
  #         go run my_tutorials/conditionals/main.go
  #      shell: bash {0}



  #go-algorithms:
  #  runs-on: 'cicd'
  #  needs: go-script
  #  steps:
  #    - name: Checkout Repository
  #      uses: actions/checkout@v2

  #    - name: Minutes To Seconds
  #      run: |
  #         go run datastructure_algorithms/convert_mins_secs/main.go
  #      shell: bash {0}
